name: Send Digest

on:
  workflow_dispatch:

env:
  RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}

permissions:
  contents: write

jobs:
  send-news-summaries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main

      - name: Install Resend Packages
        run: |
          brew install resend/cli/resend

      - name: Send Email via Resend
        run: |
          # Get the latest file
          latest_file=$(ls summaries/ | sort | tail -n1)
          
          # Build JSON payload using jq with file input
          json_payload=$(jq -n \
            --arg to "barbara@mechanicalgirl.com" \
            --arg from "barbara@mechanicalgirl.com" \
            --arg subject "Latest Summary File" \
            --rawfile content "summaries/$latest_file" \
            '{
                personalizations: [{ to: [{ email: $to }] }],
                from: { email: $from },
                subject: $subject,
                content: [{ type: "text/plain", value: $content }]
            }')

          resend --api-key ${{ secrets.RESEND_API_KEY }} emails send \
            --from "FeedMe <noreply@feedme-reader.com>" \
            --to barbara@mechanicalgirl.com \
            --subject "Latest Summary File" \
            --text-file "$json_payload"
