name: Send Digest Testing

on:
  workflow_dispatch:

env:
  RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}

permissions:
  contents: write

jobs:
  send-news-summaries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main

      - name: Install Resend Packages
        run: |
          brew install resend/cli/resend

      - name: Send Email via Resend
        run: |
          latest_file=$(ls summaries/ | sort | tail -n1)
          resend --api-key ${{ secrets.RESEND_API_KEY }} emails send \
            --from "FeedMe <noreply@feedme-reader.com>" \
            --to barbara@mechanicalgirl.com \
            --subject "Latest Summary File" \
            --text-file summaries/$latest_file
